version: '3'
services:
  redis-master:
    container_name: redis-master
    image: redis:4-alpine
    ports:
      - "6379:6379"
    networks:
      - redis-cluster-network
  redis-slave:
    container_name: redis-slave
    command: redis-server --slaveof redis-master 6379
    image: redis:4-alpine
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    networks:
      - redis-cluster-network
  redis-sentinal:
    container_name: redis-sentinal
    image: redis:4-alpine
    volumes:
      - ./redis-sentinel.conf:/etc/redis-sentinel/redis-sentinel.conf
    ports:
      - "26379:26379"
    command: redis-server /etc/redis-sentinel/redis-sentinel.conf --sentinel
    depends_on:
      - redis-master
      - redis-slave
    networks:
      - redis-cluster-network
networks:
  redis-cluster-network:
    driver: bridge
